### PR TITLE
LPS-84119 Rename vars

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey @JoyceWang08211 

https://issues.liferay.com/browse/LPS-109958

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by JoyceWang08211** [comment]
The failure is related to this pull:
1. SF issue:
https://gist.github.com/JoyceWang08211/8d3dedb007ace527d01506fa730f324c

The failures are not related to this pull:
2. The functional failure under **ContentPagesWithMapping#CreateContentWithExistingStructureViaInlineFieldWithoutMappingRequiredField** is a test-fix which will be fixed under LRQA-56430.
3. The functional failure under **Elasticsearch7.ElasticsearchRemoteClusterSmoke** has reported in LRQA-56232.
4. The functional failure under **FormRules#ConfigureShowRuleUsingAndCondition** is a flaky issue.
5. The functional failure under **Locale#ChangesToInstanceTimeZoneDoNotPropagateToExistingUsers** will be fixed under LRQA-56455.

**Comment by JoyceWang08211** [comment]
forwarded to: https://github.com/brianchandotcom/liferay-portal/pull/86006

**Pull request closed without merging**
