### PR TITLE
LPS-132326 Updated MFA test cases

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
https://issues.liferay.com/browse/LPS-132326

Please **remove** 6c2b832 when forwarding!

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:test:sf

**Comment by gaborlovasdotcom** [comment]
ci:test:mfa:nocompile

**Comment by gaborlovasdotcom** [comment]
I removed the MFA test suite commit, it will be added in a separate ticket [LPS-132616](https://issues.liferay.com/browse/LPS-132616)

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
MFA tests passed in: https://github.com/gaborlovasdotcom/liferay-portal/pull/74
[Testray results](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1534337141&testrayRunId=1534337166)

**Comment by JoyceWang08211** [comment]
Add additional fixs and forward to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/102213

**Pull request closed without merging**
