### PR TITLE
LRQA-74978

### PR DESCRIPTION
**Pull request by JoyceWang08211**

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:stop

**Comment by JoyceWang08211** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:security:nocompile

**Comment by gaborlovasdotcom** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:security:nocompile

**Comment by JoyceWang08211** [comment]
Continued in [PR#77](https://github.com/JoyceWang08211/liferay-portal/pull/77)

**Pull request closed without merging**
