### PR TITLE
LRQA-78789 Temp

### PR DESCRIPTION
**Pull request by JoyceWang08211**

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:staging-custom-db:nocompile

**Review by gaborlovasdotcom — COMMENTED** [review]
The "rebuild.staging.database" property wasn't added to the test case file, so it didn't execute the newly defined ant target.

**Comment by JoyceWang08211** [comment]
> The "rebuild.staging.database" property wasn't added to the test case file, so it didn't execute the newly defined ant target.

I defined "[rebuild.staging.database](https://github.com/JoyceWang08211/liferay-portal/pull/140/files#diff-0dc5a96f7041113b3e2e0777ee0f3118e2b6bb53b4bd82a73ebd5228e8ee4da7R7672)" property in the staging-custom-db test suite. So ideally, this property should be true automatically when trigger **ci:test:staging-custom-db**

cc @gaborlovasdotcom

**Comment by JoyceWang08211** [comment]
ci:test:staging-custom-db:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging-custom-db:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging-custom-db:nocompile

**Comment by JoyceWang08211** [comment]
ci:test:staging-custom-db:nocompile

**Pull request closed without merging**
