### PR TITLE
LRQA-66517, LRQA-66528, LRQA-66529

### PR DESCRIPTION
**Pull request by moltam89**
https://issues.liferay.com/browse/LRQA-66517
https://issues.liferay.com/browse/LRQA-66528
https://issues.liferay.com/browse/LRQA-66529

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Rebase and resolve the conflict under https://github.com/JoyceWang08211/liferay-portal/pull/252

**Pull request closed without merging**
