### PR TITLE
LRQA-66196 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-66196

master only, thx

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:oauth2:nocompile

**Comment by JoyceWang08211** [comment]
LocalFile.OAuth2#RememberDeviceWithMultipleAuth and LocalFile.OAuth2#RememberDeviceWithMultipleAuthWithoutSession are passed on local with the above commits. The other failling tests are not related to the above commits. Safe to forward to BChan.

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
cc @weller0246 @gaborlovasdotcom

**Review by gaborlovasdotcom — COMMENTED** [review]
LGTM

**Review by gaborlovasdotcom — COMMENTED** [review]
LGTM

**Pull request closed without merging**
