### PR TITLE
LRQA-66785 | master

### PR DESCRIPTION
**Pull request by moltam89**
https://issues.liferay.com/browse/LRQA-66785

master only, thx

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1057401_7962

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1057401_7962

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1057401_7962

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:reevaluate:1057401_7962

**Comment by JoyceWang08211** [comment]
The above failures of functional tests are due to [LPS-131168](https://issues.liferay.com/browse/LPS-131168)

**Comment by JoyceWang08211** [comment]
Will send to BChan directly.

**Comment by JoyceWang08211** [comment]
Not sure if LocalFile.DatabasePartitioning#AddNewCompany is caused by this PR, rerun ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
