### PR TITLE
LPS-123156 As a Content Publisher, I want to have clear distinction among Staging and Publications UI labels and phrases

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:bundle

**Comment by JoyceWang08211** [comment]
Just started reviewing :)

**Comment by JoyceWang08211** [comment]
1. The failure of [modules-integration-mysql57-jdk8/0|https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456594/AXIS_VARIABLE=6,label_exp=!master/consoleFull] is a time-out issue, has passed in the previous run. 
{code}
[exec] com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ExportLayoutPageTemplateEntriesMVCResourceCommandTest > testGetFileMultipleLayoutPageTemplatesSingleCollection FAILED
     [exec]     java.lang.IllegalStateException: Timed out while waiting for service com.liferay.portal.kernel.portlet.bridges.mvc.MVCResourceCommand mvc.command.name=/layout_page_template_admin/export_layout_page_template_entry
{code}

2. The failure of [modules-semantic-versioning-jdk8/0|https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451702/AXIS_VARIABLE=0,label_exp=!master/consoleFull]
{code}
 [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.journal.configuration                  CHANGED    3.1.0      3.1.0      3.1.1      VERSION INCREASE REQUIRED
     [echo] 	~   interface  com.liferay.journal.configuration.JournalServiceConfiguration
     [echo] 		~   method     singleAssetPublishIncludeVersionHistory()
     [echo] 			~   annotated  aQute.bnd.annotation.metatype.Meta$AD
     [echo] 				-   property   description='single-asset-publish-includes-version-history-help'
     [echo] 				+   property   description='single-asset-publish-process-includes-version-history-help'
     [echo] 				-   property   name='single-asset-publish-includes-version-history'
     [echo] 				+   property   name='single-asset-publish-process-includes-version-history'
[stopwatch] [run.batch.test.action: 5:52.432 sec]
     [echo] Semantic versioning is incorrect.
{code}
Need to fix the semantic version. @moltam89 

3. Fix the functional failure of [PGStaging#PublishPrivatePage|https://testray.liferay.com/reports/production/logs/test-1-21/1605889140674/test-portal-acceptance-pullrequest(master)/7169/functional-tomcat90-mysql57-jdk8/2/2/LocalFile.PGStaging_PublishPrivatePage/index.html.gz] under LRQA-63209.

**Comment by JoyceWang08211** [comment]
Resolve the above issues and resend [here](https://github.com/JoyceWang08211/liferay-portal/pull/190)

**Pull request closed without merging**
