### PR TITLE
LPS-191615 CI Test

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-190491
https://liferay.atlassian.net/browse/LPS-191615

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by stian-sigvartsen** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Comment by JoyceWang08211** [comment]
ci:test:oauth2

**Pull request closed without merging**
